name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main", "master" ]  # Obsługa obu typowych nazw gałęzi głównej
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main", "master" ]
  workflow_dispatch:  # Dodaje możliwość ręcznego uruchomienia workflow

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    env:
      NPM_CONFIG_LEGACY_PEER_DEPS: true  # Globalna flaga dla npm - rozwiązuje problem z react-canvas-draw
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Create Frontend Structure
      run: |
        mkdir -p frontend/public
        mkdir -p frontend/src
    
    - name: Create index.html
      run: |
        cat > frontend/public/index.html << 'EOL'
        <!DOCTYPE html>
        <html lang="pl">
          <head>
            <meta charset="utf-8" />
            <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="theme-color" content="#000000" />
            <meta name="description" content="Web app created with Create React App" />
            <title>Aplikacja do rysowania i czatu</title>
          </head>
          <body>
            <noscript>You need to enable JavaScript to run this app.</noscript>
            <div id="root"></div>
          </body>
        </html>
        EOL
    
    - name: Create index.js
      run: |
        cat > frontend/src/index.js << 'EOL'
        import React from 'react';
        import ReactDOM from 'react-dom';
        import App from './App';
        
        ReactDOM.render(
          <React.StrictMode>
            <App />
          </React.StrictMode>,
          document.getElementById('root')
        );
        EOL
    
    - name: Create or Update package.json
      working-directory: frontend
      run: |
        if [ ! -f "package.json" ]; then
          cat > package.json << 'EOL'
          {
            "name": "drawing-chat-app",
            "version": "0.1.0",
            "private": true,
            "dependencies": {
              "react": "^17.0.2",
              "react-dom": "^17.0.2",
              "react-scripts": "5.0.1",
              "react-canvas-draw": "^1.2.1"
            },
            "scripts": {
              "start": "react-scripts start",
              "build": "react-scripts build",
              "test": "react-scripts test",
              "eject": "react-scripts eject"
            },
            "browserslist": {
              "production": [
                ">0.2%",
                "not dead",
                "not op_mini all"
              ],
              "development": [
                "last 1 chrome version",
                "last 1 firefox version",
                "last 1 safari version"
              ]
            }
          }
          EOL
        fi
    
    - name: Install Frontend Dependencies
      working-directory: frontend
      run: npm install --legacy-peer-deps
    
    - name: Create App.jsx
      run: cp -f "$(pwd)/src/App.jsx" frontend/src/App.jsx || cp -f "$(pwd)/src/App.js" frontend/src/App.jsx || echo "File not found, will use existing App.jsx"
    
    - name: Build Frontend
      working-directory: frontend
      run: npm run build
      env:
        CI: false  # Zapobiega traktowaniu ostrzeżeń jako błędów
    
    - name: Deploy to Azure
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "frontend"
        api_location: "backend/api"
        output_location: "build"
        skip_app_build: false
        skip_api_build: false

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
