name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Frontend
      working-directory: frontend
      run: |
        npm install
        npm run build
        
    - name: Deploy to Azure
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "frontend"       # Ścieżka do kodu React
        api_location: "backend/api"    # Ścieżka do Azure Functions
        output_location: "build"       # Folder build React
